name: tweet bot

on:
  workflow_run:
    workflows: ['Ruby Gem']
    types: [completed]

jobs:
  tweet:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Run github action using docker
        uses: ethomson/send-sweet-action@v1
        with:
          status: "New commit pushd! (${{ github.repostory }})"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

